config/routes.rb
Cafewifi::Application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :reviews

  resources :venues

  resources :admin

  get 'users/account' => 'users#show' 

  root to: 'venues#index'

end

app/models/venue.rb
class Venue < ActiveRecord::Base
	
	validates :name, presence: true
	# validates :website, length: {minimum: 5}
	validates :latitude, presence: true
	validates :longitude, presence: true
	validates :latitude, uniqueness: true
	validates :longitude, uniqueness: true

	geocoded_by :address
	before_validation :geocode, if: ->(obj){ !obj.longitude.present? || !obj.latitude.present?}
	has_many :reviews
	belongs_to :venue_data
	has_one :venue_data
	belongs_to :user
	
	scope :nearby_places, lambda {|search,limit=50,distance=10| Venue.search(search,limit,distance)}


	def self.search(search,limit=50,distance=10)
		
		if search
			# find(:all, :conditions => ['name LIKE ? OR address LIKE ?', "%#{search}%" ])
			#Venue.where("name LIKE ? OR address LIKE ?", search, search)
			# Venue.near(search)
			Venue.near(search,distance)
		else
			Venue.all

		end
	end


end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    #@venues = Venue.all
    if params[:per]== "all"
      params[:per] = Venue.all.count
    end
    @venues = Venue.nearby_places(params[:search]).page(params[:page]).per(params[:per])
    
    @hash = Gmaps4rails.build_markers(@venues) do |venues, marker|
      marker.lat venues.latitude
      marker.lng venues.longitude
    end
    # @searchlocation = params[:search]
    # @search_place = search_text
    @search_presentation_string = search_text

    respond_to do |format|
      if (@venues.length == 0)
      format.html {redirect_to venues_path, notice: 'No places match your query'}
      end
      format.html
      format.json {render :json => @venues}
    end 
  end

  def find

  end

  # GET /venues/1
  # GET /venues/1.json
  def show
    @venue = Venue.find(params[:id])

    if @venue && @venue.venue_data
      attributes = @venue.venue_data.attributes
      attributes.delete("created_at")
      attributes.delete("updated_at")
      attributes.delete("venue_id")

      @venue_data=attributes

      # puts @venue_data.class
    end

  end

  # GET /venues/new
  def new
    if user_signed_in?
      @venue = Venue.new
    else
      redirect_to venues_path, notice: "You need to be signed in"
    end
  end

  # GET /venues/1/edit
  def edit
    if user_signed_in? && @venue.user == current_user
      render action: 'edit'
    else
      redirect_to venues_path, notice: "You do not have permission to edit this record"
    end
  end

  # POST /venues
  # POST /venues.json
  def create
    if user_signed_in?
      # @venue = Venue.new(venue_params)
      @venue = current_user.venues.new(venue_params)

      respond_to do |format|
        if @venue.save
          format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
          format.json { render action: 'show', status: :created, location: @venue }
        else
          format.html { render action: 'new' }
          format.json { render json: @venue.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to venues_path, notice: "You need to be signed in"
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end
    def search_text
      if !params[:search]
         return "There are #{Venue.all.count} Venues in total"
      else
         return "There are #{Venue.near(params[:search]).count} Venues Near #{params[:search].to_s}"
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name, :free_wifi, :charging, :website, :latitude, :longitude, :address, :search, :prettyaddress, :address_line_2, :postcode, :offset, :page, :rating)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper

	def google_map_api_key
		return "AIzaSyAcXzaq551g08tKs5i0WFqCZQKe4t06UOY"
	end

	def google_url_endpoint
		"http://maps.googleapis.com/maps/api/js"
	end

end

app/views/venues/_facilities.html.erb
<% if facilities %>
	<div class="row">
		<% if facilities.free_wifi? == true  %>
			<%= image_tag('wifi_icon.png', size: '16x16') %>
		<% end %>
		<% if facilities.venue_data.charging_sockets != nil  %>
			<%= image_tag('power_icon.png', size: '16x16') %>
		<% end %>
		<% if facilities.venue_data.number_of_tables != nil %>
			<%= image_tag('table_icon.png', size: '16x16') %>
		<% end %>
	</div>
<% end %>

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :free_wifi %><br>
    <%= f.check_box :free_wifi %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <input type="search" name="venue[address]" id="location-input" oninput="autoComplete()" class="form-control" value="" required="required" title="Find Places">
  </div>
  <div class="field">
    <%= f.label :charging %><br>
    <%= f.check_box :charging %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <!-- <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>  
<% end %>

app/views/venues/_result.html.erb
<div>

</div>

app/views/venues/_review.html.erb
<%= review.to_json %>

app/views/venues/_sample.html.erb
<!-- what fields would I like in the form?? -->
<!-- should have a place autosearch box, found places autofill the form elements -->
<!-- should fill the fields with the google places data -->
<!--  -->

This is sample data!!!!

<script type="text/javascript">
bacon =[2,3,4,5];

</script>

app/views/venues/_search.html.erb
<!-- here is the markup for the search box -->

<!-- <div class='searchcontainer'>
	<h3>Search for a wifi location near you</h3>
	    <input type="search" name="location-search" id="location-input" oninput="autoComplete()" class="form-control" value="" required="required" title="Find Places">
	    <h4>Radius</h4>
	    <input type="number" name="location-radius" id="inputLocation-Radius" class="form-control" value="" min="2" max="" step="1" required="required" title="">
	    <button type="button" class="btn btn-default" onclick="codeAddress()">Search</button>
	    <h4><%= link_to 'New Venue', new_venue_path %></h4>
</div>
 -->

<%= form_tag venues_path, :method => 'get' do %>
<p>
  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <%= text_field_tag :search, params[:search], class:"form-control", placeholder:"Find Wifi Enabled Venues Near ...", oninput:"autoComplete2()" %>  
    </div>
    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2"><%= select_tag :per, options_for_select([10,25,50,100,500,"all"]), {class: "form-control"} %></div>
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <%= submit_tag "Search", :name => nil, class:"btn btn-primary" %>
        <%= link_to "Clear Search", venues_path, class: "btn btn-warning" %>
      </div>   
  </div>
  <div class="row">
    <%= check_box_tag 'charging_sockets', 'true', params[:charging_sockets] %> 
    <%= label_tag 'Charging Sockets' %>
    <%= check_box_tag 'food_served', 'true', params[:food_served] %> 
    <%= label_tag 'Food Served' %>
    <%= check_box_tag 'tables', 'true', params[:tables] %> 
    <%= label_tag 'tables' %>
    <%= check_box_tag 'quiet', 'true', params[:quiet] %> 
    <%= label_tag 'Quiet' %>
    <%= check_box_tag 'free_wifi', 'true', params[:free_wifi] %> 
    <%= label_tag 'Free Wifi' %>
  </div>

</p>
<% end %>



<script>
 function codeAddress() {
    // var geocoder
    // geocoder = new google.maps.Geocoder();
    console.log(handler);
    // handler = Gmaps.build('Google');
    var address = document.getElementById('search').value;
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        console.log(results);
        handler.getMap().setCenter(results[0].geometry.location);
        // var marker = new google.maps.Marker({
        //     map: handler.getMap(),
        //     position: results[0].geometry.location
        // });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  }

  function autoComplete2(){
    var query = document.getElementById('search').value;
    geocoder.geocode({'address': query}, function(results, status){
      if (status == google.maps.GeocoderStatus.OK){
        choices = [];
        for (var i = results.length - 1; i >= 0; i--) {
          choices.push(results[i].formatted_address);
        };
        console.log(choices);
        trial = ["one","two","three"];
        console.log(trial);
        // completebox = document.getElementById("location-input");
        completebox = $('#search');
        // completebox.autocomplete("enable");
        completebox.autocomplete({source: choices});
        console.log('choices');      
        // completebox.autocomplete({source: trial});
      }
    })

  }

 </script>

app/views/venues/_search_results.html.erb
<!-- contained here is the markup for displaying search results on the page -->

app/views/venues/_stars.html.erb
<div class="row">
	<% if stars %>
		<% stars.times do |star| %>
			<span class="star"><%= image_tag('star.png', size: "16x16") %></span>	
		<% end %>
		<% (5-stars).times do |star| %>
			<span class="star"><%= image_tag('clear_star.png', size: "16x16") %></span>	
		<% end %>	
	<% end %>
	
</div>
	

app/views/venues/_venues.html.erb
<% venues.each_with_index do |venue,index| %>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 venue">
                      <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <div class="row">
                          <%= image_tag('http://placehold.it/96x96', size: "96x96") %> 
                        </div>
                      </div>
                      <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
                        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                          <div class="row">
                            <span class="venue-title"><%= " #{venue.name}" %></span>  
                          </div>
                            <% if venue.venue_data %>
                                <%= render 'stars', stars: venue.venue_data.rating %>                           
                                <%= render 'facilities', facilities: venue %>
                            <% end %>   
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 button-holder">
                          <%= link_to "Details", venue_path(venue.id), class: "btn btn-info venue-details" %>
                          <button type="button" class="btn btn-primary venue-details" onClick="centerMap(<%= venue.longitude %>,<%= venue.latitude %>,handler)">Center</button>
                        </div>
                      </div>
                    </div>
                  <% end %>

app/views/venues/edit.html.erb
<h1>Editing venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<br>
<div class="contentcontainer">
  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <div class="row searchbox">
        <%= render 'search' %>  
      </div>  
    </div>
  </div>
  <div class ="row">
    <div class='col-md-4'>
      
      <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= @search_presentation_string %></h3>
          </div>
          <div class="panel-heading">
            <%= link_to 'Download Local Venues', venues_path(params.merge({format: "json"})), class: "btn btn-warning" %>
            <% if user_signed_in? %>
              <%= link_to 'New Venue', new_venue_path, class: "btn btn-primary" %>  
            <% end %>
            
          </div>
          <div class="panel-body">
            <div class="row">
              <%= paginate @venues %>  
            </div>
            <div class="resultcontainer">
                  <%= render 'venues' , venues: @venues %>
                </div>
          </div>
      </div>
    </div>
    <div class="col-md-8"><div class ='gmap'>
        <div id='gmapuniq'></div>
    </div>
    </div>
  </div>  
</div>

<script>
$(document).ready(function(){
  // var geocoder;
  handler = Gmaps.build('Google');
  geocoder = new google.maps.Geocoder();
  handler.buildMap({ provider: {}, internal: {id: 'gmapuniq'}}, function(){
  markers = handler.addMarkers(<%= raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  console.log("something");
});


});
  // function codeAddress(){
  //   var geocoder
  //   geocoder = new google.maps.Geocoder();
  //   var address = document.getElementById('location-input').value;
  //   geocoder.geocode({'address': address}, function(results,status){
  //     if (status == google.maps.GeoCoderStatus.OK){
  //       handler.setCenter(results[0].geometry.location);
  //     } else {
  //       alert('geocode was not successful for the following reason'+ status)
  //     }

  //   });

  // };

  function centerMap(longitude, latitude, handler){ 
    // handler.panTo({lat: 22, lng: 32});
    console.log(longitude);
    console.log(latitude);


    handler.map.centerOn(new google.maps.LatLng(latitude, longitude));
    console.log("calling the centermap function");
    handler.buildMap({ provider: {zoom: 16}, internal: {id: 'gmapuniq'}}, function(){
       markers = handler.addMarkers(<%= raw @hash.to_json %>);
       handler.map.centerOn(new google.maps.LatLng(latitude, longitude));
    });

  }

  function codeAddress() {
    // var geocoder
    // geocoder = new google.maps.Geocoder();
    console.log(handler);
    // handler = Gmaps.build('Google');
    var address = document.getElementById('location-input').value;
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        console.log(results);
        handler.getMap().setCenter(results[0].geometry.location);
        // var marker = new google.maps.Marker({
        //     map: handler.getMap(),
        //     position: results[0].geometry.location
        // });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  }

  function autoComplete(){
    var query = document.getElementById('location-input').value;
    geocoder.geocode({'address': query}, function(results, status){
      if (status == google.maps.GeocoderStatus.OK){
        choices = [];
        for (var i = results.length - 1; i >= 0; i--) {
          choices.push(results[i].formatted_address);
        };
        console.log(choices);
        trial = ["one","two","three"];
        console.log(trial);
        // completebox = document.getElementById("location-input");
        completebox = $('#location-input');
        // completebox.autocomplete("enable");
        completebox.autocomplete({source: choices});
        console.log('choices');      
        // completebox.autocomplete({source: trial});
      }
    })

  }

</script>
<!-- <h2><%= @hash %></h2> -->

app/views/venues/new.html.erb
<br>

<div class="row">
  <div class='col-md-3'>
    <h1>New venue</h1>
  
    <%= render 'form' %>
  
    <%= link_to 'Back', venues_path %>
  </div>

  <div class='col-md-9'>
    <div class ='gmap'>
      <div id='gmapuniq'></div>
    </div>
    <div id='location'>This is the location</div>
  </div>
</div>

<script>
var x = document.getElementById("location");
function getLocation(){
	if (navigator.geolocation){
		navigator.geolocation.getCurrentPosition(showPosition);
	} else {
		console.log("geolocation not supported");
	}
};
function showPosition(position){
	var lat_user = position.coords.latitude;
	var long_user = position.coords.longitude;
	latlong = [lat_user,long_user];
	x.innerHTML = latlong;
	return latlong
};
getLocation();

$(document).ready(function(){
  handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'gmapuniq'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": latlong[0],
      "lng": latlong[1],
      "picture": {
        "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
        "width":  55,
        "height": 36
      },
      "infowindow": "This is my location"
    }
  ]);
  // markers = handler.addMarkers(<%= raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  console.log("something");
});
});
</script>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row class show-header">
    
  </div>
  <div class="row">
    <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
      <div class="row">
        <div>
          <div id='map-container'></div>
        </div>
      </div>
      <div class="row reviews-container">
        <% if @venue.reviews %>
            <ul class="list-group">
              <% @venue.reviews.each do |review| %>
                  <li class='list-group-item'><p><%= render 'review', review: review %></p></li>
              <% end %>
            </ul>
        <% end %>
      </div>
    </div>
    <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 info-container">
      <ul class="list-group">
        <li class="list-group-item"><%= label_tag('Name: ') %>  <%= @venue.name %></li>
        <li class="list-group-item"><%= label_tag('Address: ') %><%= @venue.prettyaddress %></li>
        <li class="list-group-item"><%= label_tag('Upload Speed: ') %><%= @venue.venue_data.wifi_upload_speed %></li>
        <li class="list-group-item"><%= label_tag('Download Speed: ') %><%= @venue.venue_data.wifi_download_speed %></li>
      </ul>
    </div>
  </div>
  <div class="row">
    <% if user_signed_in?  %>
        <%= link_to "Write a Review", new_review_path %>
    <% end %>
    <%= link_to 'Edit', edit_venue_path(@venue), class: "btn" %>
    <%= link_to 'Back', venues_path, class: "btn" %>
  </div>
</div>

       
<script>

$(document).ready(function(){
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map-container'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": <%= @venue.latitude %>,
      "lng": <%= @venue.longitude %>,
      "picture": {
        "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
        "width":  55,
        "height": 36
      },
      "infowindow": "This is my location"
    }
  ]);
  // markers = handler.addMarkers(<%= raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  console.log("something");
});
});
</script>

app/views/venues/venues_old.html.erb
<% venues.each do |venue| %>
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                      <div class="row">
                        <img src="#" class="img-responsive" alt="Image">  
                      </div>
                      <%= link_to "Go To Venue Details", venue_path(venue.id), class: "btn btn-info" %>
                      <button type="button" class="btn btn-primary" onClick="centerMap(<%= venue.longitude %>,<%= venue.latitude %>,handler)">Center on Venue</button>
                    </div>
                    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                      <span class="venue-title"><%= "#{index}. #{venue.name}" %></span>
                      
                    </div>
                  </div>
                <% end %>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 result">
                    <div class="thumbnail">
                      <img data-src="#" alt="">
                      <div class="caption">
                        <div class="row">
                          <h3 class="venue-header"><%= venue.name %></h3>
                          <% if venue.free_wifi == true %>
                            <span class="glyphicon glyphicon-check app-icon"></span>
                          <% end %>
                          <% if venue.charging == true %>
                            <span class="glyphicon glyphicon-flash app-icon"></span>
                          <% end %>
                        </div>
                        <div class="row">
                          
                          <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
                            <span><h4>Website:</h4><p><%= venue.website %></p></span>
                            
                            <span><h4>Address:</h4><p><%= venue.address %></p></span>
                            
                            <p><%= venue.address_line_2 %></p>
                            <p><%= venue.postcode %></p>
                            <span><h4>Distance To:</h4></span>
                            <p><%= venue.distance_to(params[:search]).round(3) %></p>
                            
                          </div>
                        </div>
                          <%= link_to "Go To Venue Details", venue_path(venue.id), class: "btn btn-info" %>
                          <button type="button" class="btn btn-primary" onClick="centerMap(<%= venue.longitude %>,<%= venue.latitude %>,handler)">Center on Venue</button>
                      </div>
                    </div>
                  </div>
                <% end %>