config/routes.rb
Cafewifi::Application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :reviews

  resources :venues

  resources :admin

  get 'users/account' => 'users#show' 

  root to: 'venues#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cafewifi</title>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
	<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'>
	</script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>


</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<%= link_to "CafeWifi", venues_path, :class => "navbar-brand" %>
	<ul class="nav navbar-nav">
		<li class="active">
			<%= link_to 'Home', venues_path %>
		</li>
		<li>
			<% if user_signed_in? %>
				<%= link_to "My Account", users_account_path(current_user) %>	
			<% end %>
			
		<li>
			<% flash.each do |type, message| %>
  				<%= content_tag :div, message, :class => "flash #{type}" %>
			<% end %>
		</li>
		<li>
			<% if user_signed_in? %>
				<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
			<% else %>
				<%= link_to "Sign In", new_user_session_path %>
			<% end %>
		</li>
		<% if !user_signed_in? %>
		<li>
			<%= link_to "Sign up", new_user_registration_path %>	
		</li>
		<% end %>		
	</ul>
</nav>
<% flash.each do |type, message| %>
  	<%= content_tag :div, message, :class => "flash #{type}" %>
<% end %>
<br>
<br>
<br>
<%= yield %>

</body>
</html>